version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels: [Refactor]
    target-branch: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    labels: [Refactor]
    target-branch: development