repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.0'
    hooks:
      - id: poetry-export
      - id: poetry-export
        args : ["-f", "requirements.txt", "-o", "requirements-dev.txt", "--with", "dev"]
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.1'
    hooks:
    -   id: autopep8
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        name: isort
        args: ["-l 119", "--conda-env", "./venv"]