name: Radon
on:
  pull_request:
    branches: ["main", "development"]

jobs:
  comment:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install radon
      - name: Create Radon's reports
        run: |
          radon cc src/ -j >cc.json
          radon mi src/ -j >mi.json
      - name: Comment the results on the PR
        uses: Libra-foundation/radon-comment@v0.1
        with:
          cc: "cc.json"
          mi: "mi.json"
